// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the INotificationService type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SendDailyNotifications provides a mock function for the type MockService
func (_mock *MockService) SendDailyNotifications(dayRange *int) error {
	ret := _mock.Called(dayRange)

	if len(ret) == 0 {
		panic("no return value specified for SendDailyNotifications")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*int) error); ok {
		r0 = returnFunc(dayRange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SendDailyNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDailyNotifications'
type MockService_SendDailyNotifications_Call struct {
	*mock.Call
}

// SendDailyNotifications is a helper method to define mock.On call
//   - dayRange *int
func (_e *MockService_Expecter) SendDailyNotifications(dayRange interface{}) *MockService_SendDailyNotifications_Call {
	return &MockService_SendDailyNotifications_Call{Call: _e.mock.On("SendDailyNotifications", dayRange)}
}

func (_c *MockService_SendDailyNotifications_Call) Run(run func(dayRange *int)) *MockService_SendDailyNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int
		if args[0] != nil {
			arg0 = args[0].(*int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SendDailyNotifications_Call) Return(err error) *MockService_SendDailyNotifications_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SendDailyNotifications_Call) RunAndReturn(run func(dayRange *int) error) *MockService_SendDailyNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// SendNotiByPatientId provides a mock function for the type MockService
func (_mock *MockService) SendNotiByPatientId(id int, title string, body string) error {
	ret := _mock.Called(id, title, body)

	if len(ret) == 0 {
		panic("no return value specified for SendNotiByPatientId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = returnFunc(id, title, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SendNotiByPatientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNotiByPatientId'
type MockService_SendNotiByPatientId_Call struct {
	*mock.Call
}

// SendNotiByPatientId is a helper method to define mock.On call
//   - id int
//   - title string
//   - body string
func (_e *MockService_Expecter) SendNotiByPatientId(id interface{}, title interface{}, body interface{}) *MockService_SendNotiByPatientId_Call {
	return &MockService_SendNotiByPatientId_Call{Call: _e.mock.On("SendNotiByPatientId", id, title, body)}
}

func (_c *MockService_SendNotiByPatientId_Call) Run(run func(id int, title string, body string)) *MockService_SendNotiByPatientId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SendNotiByPatientId_Call) Return(err error) *MockService_SendNotiByPatientId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SendNotiByPatientId_Call) RunAndReturn(run func(id int, title string, body string) error) *MockService_SendNotiByPatientId_Call {
	_c.Call.Return(run)
	return _c
}
