packages:
  "github.com/PhasitWo/duchenne-server/repository":
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      IRepo:
        config:
          filename: repository_mock.go
          structname: MockRepo
      IGorm:
        config:
          filename: gorm_mock.go
          structname: MockGorm
  "github.com/PhasitWo/duchenne-server/services/notification":
    interfaces:
      INotificationService:
        config:
          filename: service_mock.go
          structname: MockService
