
POST http://localhost:8080/mobile/auth/login
content-type: application/json

{
    "hn" : "test1",
    "firstName" : "fn",
    "lastName" : "ln"
}
###


POST http://localhost:8080/mobile/auth/signup
content-type: application/json

{
    "hn" : "test3",
    "firstName" : "fn3",
    "middleName" : "mn3",
    "lastName" : "ln3",
    "phone" : "01111111",
    "email" : "asd@asd.com"
}

###

GET http://localhost:8080/mobile/api/profile
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDA0NzUxODF9.LGCUtfDt97E3rpVKpP62eT30-qYQfCwy6m-SwMhk-hA

###

GET http://localhost:8080/mobile/api/test
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDA0NzUxODF9.LGCUtfDt97E3rpVKpP62eT30-qYQfCwy6m-SwMhk-hA