// Code generated by mockery v2.53.3. DO NOT EDIT.

package repository

import (
	model "github.com/PhasitWo/duchenne-server/model"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockRepo is an autogenerated mock type for the IRepo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// CreateAppointment provides a mock function with given fields: appointment
func (_m *MockRepo) CreateAppointment(appointment model.Appointment) (int, error) {
	ret := _m.Called(appointment)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointment")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Appointment) (int, error)); ok {
		return rf(appointment)
	}
	if rf, ok := ret.Get(0).(func(model.Appointment) int); ok {
		r0 = rf(appointment)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Appointment) error); ok {
		r1 = rf(appointment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreateAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppointment'
type MockRepo_CreateAppointment_Call struct {
	*mock.Call
}

// CreateAppointment is a helper method to define mock.On call
//   - appointment model.Appointment
func (_e *MockRepo_Expecter) CreateAppointment(appointment interface{}) *MockRepo_CreateAppointment_Call {
	return &MockRepo_CreateAppointment_Call{Call: _e.mock.On("CreateAppointment", appointment)}
}

func (_c *MockRepo_CreateAppointment_Call) Run(run func(appointment model.Appointment)) *MockRepo_CreateAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Appointment))
	})
	return _c
}

func (_c *MockRepo_CreateAppointment_Call) Return(_a0 int, _a1 error) *MockRepo_CreateAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreateAppointment_Call) RunAndReturn(run func(model.Appointment) (int, error)) *MockRepo_CreateAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContent provides a mock function with given fields: content
func (_m *MockRepo) CreateContent(content model.Content) (int, error) {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for CreateContent")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Content) (int, error)); ok {
		return rf(content)
	}
	if rf, ok := ret.Get(0).(func(model.Content) int); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Content) error); ok {
		r1 = rf(content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreateContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContent'
type MockRepo_CreateContent_Call struct {
	*mock.Call
}

// CreateContent is a helper method to define mock.On call
//   - content model.Content
func (_e *MockRepo_Expecter) CreateContent(content interface{}) *MockRepo_CreateContent_Call {
	return &MockRepo_CreateContent_Call{Call: _e.mock.On("CreateContent", content)}
}

func (_c *MockRepo_CreateContent_Call) Run(run func(content model.Content)) *MockRepo_CreateContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Content))
	})
	return _c
}

func (_c *MockRepo_CreateContent_Call) Return(_a0 int, _a1 error) *MockRepo_CreateContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreateContent_Call) RunAndReturn(run func(model.Content) (int, error)) *MockRepo_CreateContent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDevice provides a mock function with given fields: d
func (_m *MockRepo) CreateDevice(d model.Device) (int, error) {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Device) (int, error)); ok {
		return rf(d)
	}
	if rf, ok := ret.Get(0).(func(model.Device) int); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Device) error); ok {
		r1 = rf(d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockRepo_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - d model.Device
func (_e *MockRepo_Expecter) CreateDevice(d interface{}) *MockRepo_CreateDevice_Call {
	return &MockRepo_CreateDevice_Call{Call: _e.mock.On("CreateDevice", d)}
}

func (_c *MockRepo_CreateDevice_Call) Run(run func(d model.Device)) *MockRepo_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Device))
	})
	return _c
}

func (_c *MockRepo_CreateDevice_Call) Return(_a0 int, _a1 error) *MockRepo_CreateDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreateDevice_Call) RunAndReturn(run func(model.Device) (int, error)) *MockRepo_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDoctor provides a mock function with given fields: doctor
func (_m *MockRepo) CreateDoctor(doctor model.Doctor) (int, error) {
	ret := _m.Called(doctor)

	if len(ret) == 0 {
		panic("no return value specified for CreateDoctor")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Doctor) (int, error)); ok {
		return rf(doctor)
	}
	if rf, ok := ret.Get(0).(func(model.Doctor) int); ok {
		r0 = rf(doctor)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Doctor) error); ok {
		r1 = rf(doctor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreateDoctor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDoctor'
type MockRepo_CreateDoctor_Call struct {
	*mock.Call
}

// CreateDoctor is a helper method to define mock.On call
//   - doctor model.Doctor
func (_e *MockRepo_Expecter) CreateDoctor(doctor interface{}) *MockRepo_CreateDoctor_Call {
	return &MockRepo_CreateDoctor_Call{Call: _e.mock.On("CreateDoctor", doctor)}
}

func (_c *MockRepo_CreateDoctor_Call) Run(run func(doctor model.Doctor)) *MockRepo_CreateDoctor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Doctor))
	})
	return _c
}

func (_c *MockRepo_CreateDoctor_Call) Return(_a0 int, _a1 error) *MockRepo_CreateDoctor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreateDoctor_Call) RunAndReturn(run func(model.Doctor) (int, error)) *MockRepo_CreateDoctor_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePatient provides a mock function with given fields: patient
func (_m *MockRepo) CreatePatient(patient model.Patient) (int, error) {
	ret := _m.Called(patient)

	if len(ret) == 0 {
		panic("no return value specified for CreatePatient")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Patient) (int, error)); ok {
		return rf(patient)
	}
	if rf, ok := ret.Get(0).(func(model.Patient) int); ok {
		r0 = rf(patient)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Patient) error); ok {
		r1 = rf(patient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreatePatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePatient'
type MockRepo_CreatePatient_Call struct {
	*mock.Call
}

// CreatePatient is a helper method to define mock.On call
//   - patient model.Patient
func (_e *MockRepo_Expecter) CreatePatient(patient interface{}) *MockRepo_CreatePatient_Call {
	return &MockRepo_CreatePatient_Call{Call: _e.mock.On("CreatePatient", patient)}
}

func (_c *MockRepo_CreatePatient_Call) Run(run func(patient model.Patient)) *MockRepo_CreatePatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Patient))
	})
	return _c
}

func (_c *MockRepo_CreatePatient_Call) Return(_a0 int, _a1 error) *MockRepo_CreatePatient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreatePatient_Call) RunAndReturn(run func(model.Patient) (int, error)) *MockRepo_CreatePatient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuestion provides a mock function with given fields: patientId, topic, question, createAt
func (_m *MockRepo) CreateQuestion(patientId int, topic string, question string, createAt int) (int, error) {
	ret := _m.Called(patientId, topic, question, createAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestion")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, string, int) (int, error)); ok {
		return rf(patientId, topic, question, createAt)
	}
	if rf, ok := ret.Get(0).(func(int, string, string, int) int); ok {
		r0 = rf(patientId, topic, question, createAt)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, string, string, int) error); ok {
		r1 = rf(patientId, topic, question, createAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_CreateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuestion'
type MockRepo_CreateQuestion_Call struct {
	*mock.Call
}

// CreateQuestion is a helper method to define mock.On call
//   - patientId int
//   - topic string
//   - question string
//   - createAt int
func (_e *MockRepo_Expecter) CreateQuestion(patientId interface{}, topic interface{}, question interface{}, createAt interface{}) *MockRepo_CreateQuestion_Call {
	return &MockRepo_CreateQuestion_Call{Call: _e.mock.On("CreateQuestion", patientId, topic, question, createAt)}
}

func (_c *MockRepo_CreateQuestion_Call) Run(run func(patientId int, topic string, question string, createAt int)) *MockRepo_CreateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockRepo_CreateQuestion_Call) Return(_a0 int, _a1 error) *MockRepo_CreateQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_CreateQuestion_Call) RunAndReturn(run func(int, string, string, int) (int, error)) *MockRepo_CreateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppointment provides a mock function with given fields: appointmentId
func (_m *MockRepo) DeleteAppointment(appointmentId interface{}) error {
	ret := _m.Called(appointmentId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppointment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(appointmentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeleteAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppointment'
type MockRepo_DeleteAppointment_Call struct {
	*mock.Call
}

// DeleteAppointment is a helper method to define mock.On call
//   - appointmentId interface{}
func (_e *MockRepo_Expecter) DeleteAppointment(appointmentId interface{}) *MockRepo_DeleteAppointment_Call {
	return &MockRepo_DeleteAppointment_Call{Call: _e.mock.On("DeleteAppointment", appointmentId)}
}

func (_c *MockRepo_DeleteAppointment_Call) Run(run func(appointmentId interface{})) *MockRepo_DeleteAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_DeleteAppointment_Call) Return(_a0 error) *MockRepo_DeleteAppointment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeleteAppointment_Call) RunAndReturn(run func(interface{}) error) *MockRepo_DeleteAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteContent provides a mock function with given fields: contentID
func (_m *MockRepo) DeleteContent(contentID interface{}) error {
	ret := _m.Called(contentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(contentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeleteContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteContent'
type MockRepo_DeleteContent_Call struct {
	*mock.Call
}

// DeleteContent is a helper method to define mock.On call
//   - contentID interface{}
func (_e *MockRepo_Expecter) DeleteContent(contentID interface{}) *MockRepo_DeleteContent_Call {
	return &MockRepo_DeleteContent_Call{Call: _e.mock.On("DeleteContent", contentID)}
}

func (_c *MockRepo_DeleteContent_Call) Run(run func(contentID interface{})) *MockRepo_DeleteContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_DeleteContent_Call) Return(_a0 error) *MockRepo_DeleteContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeleteContent_Call) RunAndReturn(run func(interface{}) error) *MockRepo_DeleteContent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDevice provides a mock function with given fields: deviceId
func (_m *MockRepo) DeleteDevice(deviceId interface{}) error {
	ret := _m.Called(deviceId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(deviceId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockRepo_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - deviceId interface{}
func (_e *MockRepo_Expecter) DeleteDevice(deviceId interface{}) *MockRepo_DeleteDevice_Call {
	return &MockRepo_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", deviceId)}
}

func (_c *MockRepo_DeleteDevice_Call) Run(run func(deviceId interface{})) *MockRepo_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_DeleteDevice_Call) Return(_a0 error) *MockRepo_DeleteDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeleteDevice_Call) RunAndReturn(run func(interface{}) error) *MockRepo_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDoctorById provides a mock function with given fields: id
func (_m *MockRepo) DeleteDoctorById(id interface{}) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDoctorById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeleteDoctorById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDoctorById'
type MockRepo_DeleteDoctorById_Call struct {
	*mock.Call
}

// DeleteDoctorById is a helper method to define mock.On call
//   - id interface{}
func (_e *MockRepo_Expecter) DeleteDoctorById(id interface{}) *MockRepo_DeleteDoctorById_Call {
	return &MockRepo_DeleteDoctorById_Call{Call: _e.mock.On("DeleteDoctorById", id)}
}

func (_c *MockRepo_DeleteDoctorById_Call) Run(run func(id interface{})) *MockRepo_DeleteDoctorById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_DeleteDoctorById_Call) Return(_a0 error) *MockRepo_DeleteDoctorById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeleteDoctorById_Call) RunAndReturn(run func(interface{}) error) *MockRepo_DeleteDoctorById_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePatientById provides a mock function with given fields: id
func (_m *MockRepo) DeletePatientById(id interface{}) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePatientById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeletePatientById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePatientById'
type MockRepo_DeletePatientById_Call struct {
	*mock.Call
}

// DeletePatientById is a helper method to define mock.On call
//   - id interface{}
func (_e *MockRepo_Expecter) DeletePatientById(id interface{}) *MockRepo_DeletePatientById_Call {
	return &MockRepo_DeletePatientById_Call{Call: _e.mock.On("DeletePatientById", id)}
}

func (_c *MockRepo_DeletePatientById_Call) Run(run func(id interface{})) *MockRepo_DeletePatientById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_DeletePatientById_Call) Return(_a0 error) *MockRepo_DeletePatientById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeletePatientById_Call) RunAndReturn(run func(interface{}) error) *MockRepo_DeletePatientById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuestion provides a mock function with given fields: questionId
func (_m *MockRepo) DeleteQuestion(questionId interface{}) error {
	ret := _m.Called(questionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(questionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_DeleteQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestion'
type MockRepo_DeleteQuestion_Call struct {
	*mock.Call
}

// DeleteQuestion is a helper method to define mock.On call
//   - questionId interface{}
func (_e *MockRepo_Expecter) DeleteQuestion(questionId interface{}) *MockRepo_DeleteQuestion_Call {
	return &MockRepo_DeleteQuestion_Call{Call: _e.mock.On("DeleteQuestion", questionId)}
}

func (_c *MockRepo_DeleteQuestion_Call) Run(run func(questionId interface{})) *MockRepo_DeleteQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_DeleteQuestion_Call) Return(_a0 error) *MockRepo_DeleteQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_DeleteQuestion_Call) RunAndReturn(run func(interface{}) error) *MockRepo_DeleteQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAppointment provides a mock function with given fields: limit, offset, criteria
func (_m *MockRepo) GetAllAppointment(limit int, offset int, criteria ...Criteria) ([]model.SafeAppointment, error) {
	_va := make([]interface{}, len(criteria))
	for _i := range criteria {
		_va[_i] = criteria[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, limit, offset)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAppointment")
	}

	var r0 []model.SafeAppointment
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, ...Criteria) ([]model.SafeAppointment, error)); ok {
		return rf(limit, offset, criteria...)
	}
	if rf, ok := ret.Get(0).(func(int, int, ...Criteria) []model.SafeAppointment); ok {
		r0 = rf(limit, offset, criteria...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SafeAppointment)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, ...Criteria) error); ok {
		r1 = rf(limit, offset, criteria...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAllAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAppointment'
type MockRepo_GetAllAppointment_Call struct {
	*mock.Call
}

// GetAllAppointment is a helper method to define mock.On call
//   - limit int
//   - offset int
//   - criteria ...Criteria
func (_e *MockRepo_Expecter) GetAllAppointment(limit interface{}, offset interface{}, criteria ...interface{}) *MockRepo_GetAllAppointment_Call {
	return &MockRepo_GetAllAppointment_Call{Call: _e.mock.On("GetAllAppointment",
		append([]interface{}{limit, offset}, criteria...)...)}
}

func (_c *MockRepo_GetAllAppointment_Call) Run(run func(limit int, offset int, criteria ...Criteria)) *MockRepo_GetAllAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]Criteria, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(Criteria)
			}
		}
		run(args[0].(int), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockRepo_GetAllAppointment_Call) Return(_a0 []model.SafeAppointment, _a1 error) *MockRepo_GetAllAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAllAppointment_Call) RunAndReturn(run func(int, int, ...Criteria) ([]model.SafeAppointment, error)) *MockRepo_GetAllAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllContent provides a mock function with given fields: limit, offset, criteria
func (_m *MockRepo) GetAllContent(limit int, offset int, criteria ...Criteria) ([]model.Content, error) {
	_va := make([]interface{}, len(criteria))
	for _i := range criteria {
		_va[_i] = criteria[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, limit, offset)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAllContent")
	}

	var r0 []model.Content
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, ...Criteria) ([]model.Content, error)); ok {
		return rf(limit, offset, criteria...)
	}
	if rf, ok := ret.Get(0).(func(int, int, ...Criteria) []model.Content); ok {
		r0 = rf(limit, offset, criteria...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Content)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, ...Criteria) error); ok {
		r1 = rf(limit, offset, criteria...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAllContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllContent'
type MockRepo_GetAllContent_Call struct {
	*mock.Call
}

// GetAllContent is a helper method to define mock.On call
//   - limit int
//   - offset int
//   - criteria ...Criteria
func (_e *MockRepo_Expecter) GetAllContent(limit interface{}, offset interface{}, criteria ...interface{}) *MockRepo_GetAllContent_Call {
	return &MockRepo_GetAllContent_Call{Call: _e.mock.On("GetAllContent",
		append([]interface{}{limit, offset}, criteria...)...)}
}

func (_c *MockRepo_GetAllContent_Call) Run(run func(limit int, offset int, criteria ...Criteria)) *MockRepo_GetAllContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]Criteria, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(Criteria)
			}
		}
		run(args[0].(int), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockRepo_GetAllContent_Call) Return(_a0 []model.Content, _a1 error) *MockRepo_GetAllContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAllContent_Call) RunAndReturn(run func(int, int, ...Criteria) ([]model.Content, error)) *MockRepo_GetAllContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDevice provides a mock function with given fields: criteria
func (_m *MockRepo) GetAllDevice(criteria ...Criteria) ([]model.Device, error) {
	_va := make([]interface{}, len(criteria))
	for _i := range criteria {
		_va[_i] = criteria[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDevice")
	}

	var r0 []model.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(...Criteria) ([]model.Device, error)); ok {
		return rf(criteria...)
	}
	if rf, ok := ret.Get(0).(func(...Criteria) []model.Device); ok {
		r0 = rf(criteria...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(...Criteria) error); ok {
		r1 = rf(criteria...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAllDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDevice'
type MockRepo_GetAllDevice_Call struct {
	*mock.Call
}

// GetAllDevice is a helper method to define mock.On call
//   - criteria ...Criteria
func (_e *MockRepo_Expecter) GetAllDevice(criteria ...interface{}) *MockRepo_GetAllDevice_Call {
	return &MockRepo_GetAllDevice_Call{Call: _e.mock.On("GetAllDevice",
		append([]interface{}{}, criteria...)...)}
}

func (_c *MockRepo_GetAllDevice_Call) Run(run func(criteria ...Criteria)) *MockRepo_GetAllDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]Criteria, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(Criteria)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockRepo_GetAllDevice_Call) Return(_a0 []model.Device, _a1 error) *MockRepo_GetAllDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAllDevice_Call) RunAndReturn(run func(...Criteria) ([]model.Device, error)) *MockRepo_GetAllDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDoctor provides a mock function with no fields
func (_m *MockRepo) GetAllDoctor() ([]model.TrimDoctor, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllDoctor")
	}

	var r0 []model.TrimDoctor
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.TrimDoctor, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.TrimDoctor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TrimDoctor)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAllDoctor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDoctor'
type MockRepo_GetAllDoctor_Call struct {
	*mock.Call
}

// GetAllDoctor is a helper method to define mock.On call
func (_e *MockRepo_Expecter) GetAllDoctor() *MockRepo_GetAllDoctor_Call {
	return &MockRepo_GetAllDoctor_Call{Call: _e.mock.On("GetAllDoctor")}
}

func (_c *MockRepo_GetAllDoctor_Call) Run(run func()) *MockRepo_GetAllDoctor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepo_GetAllDoctor_Call) Return(_a0 []model.TrimDoctor, _a1 error) *MockRepo_GetAllDoctor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAllDoctor_Call) RunAndReturn(run func() ([]model.TrimDoctor, error)) *MockRepo_GetAllDoctor_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPatient provides a mock function with no fields
func (_m *MockRepo) GetAllPatient() ([]model.Patient, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPatient")
	}

	var r0 []model.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Patient, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Patient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAllPatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPatient'
type MockRepo_GetAllPatient_Call struct {
	*mock.Call
}

// GetAllPatient is a helper method to define mock.On call
func (_e *MockRepo_Expecter) GetAllPatient() *MockRepo_GetAllPatient_Call {
	return &MockRepo_GetAllPatient_Call{Call: _e.mock.On("GetAllPatient")}
}

func (_c *MockRepo_GetAllPatient_Call) Run(run func()) *MockRepo_GetAllPatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepo_GetAllPatient_Call) Return(_a0 []model.Patient, _a1 error) *MockRepo_GetAllPatient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAllPatient_Call) RunAndReturn(run func() ([]model.Patient, error)) *MockRepo_GetAllPatient_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllQuestion provides a mock function with given fields: limit, offset, criteria
func (_m *MockRepo) GetAllQuestion(limit int, offset int, criteria ...Criteria) ([]model.QuestionTopic, error) {
	_va := make([]interface{}, len(criteria))
	for _i := range criteria {
		_va[_i] = criteria[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, limit, offset)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAllQuestion")
	}

	var r0 []model.QuestionTopic
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, ...Criteria) ([]model.QuestionTopic, error)); ok {
		return rf(limit, offset, criteria...)
	}
	if rf, ok := ret.Get(0).(func(int, int, ...Criteria) []model.QuestionTopic); ok {
		r0 = rf(limit, offset, criteria...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.QuestionTopic)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, ...Criteria) error); ok {
		r1 = rf(limit, offset, criteria...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAllQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllQuestion'
type MockRepo_GetAllQuestion_Call struct {
	*mock.Call
}

// GetAllQuestion is a helper method to define mock.On call
//   - limit int
//   - offset int
//   - criteria ...Criteria
func (_e *MockRepo_Expecter) GetAllQuestion(limit interface{}, offset interface{}, criteria ...interface{}) *MockRepo_GetAllQuestion_Call {
	return &MockRepo_GetAllQuestion_Call{Call: _e.mock.On("GetAllQuestion",
		append([]interface{}{limit, offset}, criteria...)...)}
}

func (_c *MockRepo_GetAllQuestion_Call) Run(run func(limit int, offset int, criteria ...Criteria)) *MockRepo_GetAllQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]Criteria, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(Criteria)
			}
		}
		run(args[0].(int), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockRepo_GetAllQuestion_Call) Return(_a0 []model.QuestionTopic, _a1 error) *MockRepo_GetAllQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAllQuestion_Call) RunAndReturn(run func(int, int, ...Criteria) ([]model.QuestionTopic, error)) *MockRepo_GetAllQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppointment provides a mock function with given fields: appointmentId
func (_m *MockRepo) GetAppointment(appointmentId interface{}) (model.SafeAppointment, error) {
	ret := _m.Called(appointmentId)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointment")
	}

	var r0 model.SafeAppointment
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (model.SafeAppointment, error)); ok {
		return rf(appointmentId)
	}
	if rf, ok := ret.Get(0).(func(interface{}) model.SafeAppointment); ok {
		r0 = rf(appointmentId)
	} else {
		r0 = ret.Get(0).(model.SafeAppointment)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(appointmentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppointment'
type MockRepo_GetAppointment_Call struct {
	*mock.Call
}

// GetAppointment is a helper method to define mock.On call
//   - appointmentId interface{}
func (_e *MockRepo_Expecter) GetAppointment(appointmentId interface{}) *MockRepo_GetAppointment_Call {
	return &MockRepo_GetAppointment_Call{Call: _e.mock.On("GetAppointment", appointmentId)}
}

func (_c *MockRepo_GetAppointment_Call) Run(run func(appointmentId interface{})) *MockRepo_GetAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_GetAppointment_Call) Return(_a0 model.SafeAppointment, _a1 error) *MockRepo_GetAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetAppointment_Call) RunAndReturn(run func(interface{}) (model.SafeAppointment, error)) *MockRepo_GetAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// GetContent provides a mock function with given fields: contentID
func (_m *MockRepo) GetContent(contentID interface{}) (model.Content, error) {
	ret := _m.Called(contentID)

	if len(ret) == 0 {
		panic("no return value specified for GetContent")
	}

	var r0 model.Content
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (model.Content, error)); ok {
		return rf(contentID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) model.Content); ok {
		r0 = rf(contentID)
	} else {
		r0 = ret.Get(0).(model.Content)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(contentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContent'
type MockRepo_GetContent_Call struct {
	*mock.Call
}

// GetContent is a helper method to define mock.On call
//   - contentID interface{}
func (_e *MockRepo_Expecter) GetContent(contentID interface{}) *MockRepo_GetContent_Call {
	return &MockRepo_GetContent_Call{Call: _e.mock.On("GetContent", contentID)}
}

func (_c *MockRepo_GetContent_Call) Run(run func(contentID interface{})) *MockRepo_GetContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_GetContent_Call) Return(_a0 model.Content, _a1 error) *MockRepo_GetContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetContent_Call) RunAndReturn(run func(interface{}) (model.Content, error)) *MockRepo_GetContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetDoctorById provides a mock function with given fields: id
func (_m *MockRepo) GetDoctorById(id interface{}) (model.Doctor, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDoctorById")
	}

	var r0 model.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (model.Doctor, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(interface{}) model.Doctor); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Doctor)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetDoctorById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDoctorById'
type MockRepo_GetDoctorById_Call struct {
	*mock.Call
}

// GetDoctorById is a helper method to define mock.On call
//   - id interface{}
func (_e *MockRepo_Expecter) GetDoctorById(id interface{}) *MockRepo_GetDoctorById_Call {
	return &MockRepo_GetDoctorById_Call{Call: _e.mock.On("GetDoctorById", id)}
}

func (_c *MockRepo_GetDoctorById_Call) Run(run func(id interface{})) *MockRepo_GetDoctorById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_GetDoctorById_Call) Return(_a0 model.Doctor, _a1 error) *MockRepo_GetDoctorById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetDoctorById_Call) RunAndReturn(run func(interface{}) (model.Doctor, error)) *MockRepo_GetDoctorById_Call {
	_c.Call.Return(run)
	return _c
}

// GetDoctorByUsername provides a mock function with given fields: username
func (_m *MockRepo) GetDoctorByUsername(username string) (model.Doctor, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetDoctorByUsername")
	}

	var r0 model.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.Doctor, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) model.Doctor); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(model.Doctor)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetDoctorByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDoctorByUsername'
type MockRepo_GetDoctorByUsername_Call struct {
	*mock.Call
}

// GetDoctorByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockRepo_Expecter) GetDoctorByUsername(username interface{}) *MockRepo_GetDoctorByUsername_Call {
	return &MockRepo_GetDoctorByUsername_Call{Call: _e.mock.On("GetDoctorByUsername", username)}
}

func (_c *MockRepo_GetDoctorByUsername_Call) Run(run func(username string)) *MockRepo_GetDoctorByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepo_GetDoctorByUsername_Call) Return(_a0 model.Doctor, _a1 error) *MockRepo_GetDoctorByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetDoctorByUsername_Call) RunAndReturn(run func(string) (model.Doctor, error)) *MockRepo_GetDoctorByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetPatientByHN provides a mock function with given fields: hn
func (_m *MockRepo) GetPatientByHN(hn string) (model.Patient, error) {
	ret := _m.Called(hn)

	if len(ret) == 0 {
		panic("no return value specified for GetPatientByHN")
	}

	var r0 model.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.Patient, error)); ok {
		return rf(hn)
	}
	if rf, ok := ret.Get(0).(func(string) model.Patient); ok {
		r0 = rf(hn)
	} else {
		r0 = ret.Get(0).(model.Patient)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetPatientByHN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPatientByHN'
type MockRepo_GetPatientByHN_Call struct {
	*mock.Call
}

// GetPatientByHN is a helper method to define mock.On call
//   - hn string
func (_e *MockRepo_Expecter) GetPatientByHN(hn interface{}) *MockRepo_GetPatientByHN_Call {
	return &MockRepo_GetPatientByHN_Call{Call: _e.mock.On("GetPatientByHN", hn)}
}

func (_c *MockRepo_GetPatientByHN_Call) Run(run func(hn string)) *MockRepo_GetPatientByHN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepo_GetPatientByHN_Call) Return(_a0 model.Patient, _a1 error) *MockRepo_GetPatientByHN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetPatientByHN_Call) RunAndReturn(run func(string) (model.Patient, error)) *MockRepo_GetPatientByHN_Call {
	_c.Call.Return(run)
	return _c
}

// GetPatientById provides a mock function with given fields: id
func (_m *MockRepo) GetPatientById(id interface{}) (model.Patient, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPatientById")
	}

	var r0 model.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (model.Patient, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(interface{}) model.Patient); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Patient)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetPatientById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPatientById'
type MockRepo_GetPatientById_Call struct {
	*mock.Call
}

// GetPatientById is a helper method to define mock.On call
//   - id interface{}
func (_e *MockRepo_Expecter) GetPatientById(id interface{}) *MockRepo_GetPatientById_Call {
	return &MockRepo_GetPatientById_Call{Call: _e.mock.On("GetPatientById", id)}
}

func (_c *MockRepo_GetPatientById_Call) Run(run func(id interface{})) *MockRepo_GetPatientById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_GetPatientById_Call) Return(_a0 model.Patient, _a1 error) *MockRepo_GetPatientById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetPatientById_Call) RunAndReturn(run func(interface{}) (model.Patient, error)) *MockRepo_GetPatientById_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestion provides a mock function with given fields: questionId
func (_m *MockRepo) GetQuestion(questionId interface{}) (model.SafeQuestion, error) {
	ret := _m.Called(questionId)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestion")
	}

	var r0 model.SafeQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (model.SafeQuestion, error)); ok {
		return rf(questionId)
	}
	if rf, ok := ret.Get(0).(func(interface{}) model.SafeQuestion); ok {
		r0 = rf(questionId)
	} else {
		r0 = ret.Get(0).(model.SafeQuestion)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(questionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepo_GetQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestion'
type MockRepo_GetQuestion_Call struct {
	*mock.Call
}

// GetQuestion is a helper method to define mock.On call
//   - questionId interface{}
func (_e *MockRepo_Expecter) GetQuestion(questionId interface{}) *MockRepo_GetQuestion_Call {
	return &MockRepo_GetQuestion_Call{Call: _e.mock.On("GetQuestion", questionId)}
}

func (_c *MockRepo_GetQuestion_Call) Run(run func(questionId interface{})) *MockRepo_GetQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRepo_GetQuestion_Call) Return(_a0 model.SafeQuestion, _a1 error) *MockRepo_GetQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepo_GetQuestion_Call) RunAndReturn(run func(interface{}) (model.SafeQuestion, error)) *MockRepo_GetQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function with given fields: db
func (_m *MockRepo) New(db *gorm.DB) IRepo {
	ret := _m.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 IRepo
	if rf, ok := ret.Get(0).(func(*gorm.DB) IRepo); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IRepo)
		}
	}

	return r0
}

// MockRepo_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockRepo_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockRepo_Expecter) New(db interface{}) *MockRepo_New_Call {
	return &MockRepo_New_Call{Call: _e.mock.On("New", db)}
}

func (_c *MockRepo_New_Call) Run(run func(db *gorm.DB)) *MockRepo_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockRepo_New_Call) Return(_a0 IRepo) *MockRepo_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_New_Call) RunAndReturn(run func(*gorm.DB) IRepo) *MockRepo_New_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAppointment provides a mock function with given fields: appointment
func (_m *MockRepo) UpdateAppointment(appointment model.Appointment) error {
	ret := _m.Called(appointment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAppointment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Appointment) error); ok {
		r0 = rf(appointment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdateAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAppointment'
type MockRepo_UpdateAppointment_Call struct {
	*mock.Call
}

// UpdateAppointment is a helper method to define mock.On call
//   - appointment model.Appointment
func (_e *MockRepo_Expecter) UpdateAppointment(appointment interface{}) *MockRepo_UpdateAppointment_Call {
	return &MockRepo_UpdateAppointment_Call{Call: _e.mock.On("UpdateAppointment", appointment)}
}

func (_c *MockRepo_UpdateAppointment_Call) Run(run func(appointment model.Appointment)) *MockRepo_UpdateAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Appointment))
	})
	return _c
}

func (_c *MockRepo_UpdateAppointment_Call) Return(_a0 error) *MockRepo_UpdateAppointment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdateAppointment_Call) RunAndReturn(run func(model.Appointment) error) *MockRepo_UpdateAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateContent provides a mock function with given fields: content
func (_m *MockRepo) UpdateContent(content model.Content) error {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Content) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdateContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateContent'
type MockRepo_UpdateContent_Call struct {
	*mock.Call
}

// UpdateContent is a helper method to define mock.On call
//   - content model.Content
func (_e *MockRepo_Expecter) UpdateContent(content interface{}) *MockRepo_UpdateContent_Call {
	return &MockRepo_UpdateContent_Call{Call: _e.mock.On("UpdateContent", content)}
}

func (_c *MockRepo_UpdateContent_Call) Run(run func(content model.Content)) *MockRepo_UpdateContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Content))
	})
	return _c
}

func (_c *MockRepo_UpdateContent_Call) Return(_a0 error) *MockRepo_UpdateContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdateContent_Call) RunAndReturn(run func(model.Content) error) *MockRepo_UpdateContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDevice provides a mock function with given fields: d
func (_m *MockRepo) UpdateDevice(d model.Device) error {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Device) error); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockRepo_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - d model.Device
func (_e *MockRepo_Expecter) UpdateDevice(d interface{}) *MockRepo_UpdateDevice_Call {
	return &MockRepo_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", d)}
}

func (_c *MockRepo_UpdateDevice_Call) Run(run func(d model.Device)) *MockRepo_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Device))
	})
	return _c
}

func (_c *MockRepo_UpdateDevice_Call) Return(_a0 error) *MockRepo_UpdateDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdateDevice_Call) RunAndReturn(run func(model.Device) error) *MockRepo_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDoctor provides a mock function with given fields: doctor
func (_m *MockRepo) UpdateDoctor(doctor model.Doctor) error {
	ret := _m.Called(doctor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDoctor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Doctor) error); ok {
		r0 = rf(doctor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdateDoctor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDoctor'
type MockRepo_UpdateDoctor_Call struct {
	*mock.Call
}

// UpdateDoctor is a helper method to define mock.On call
//   - doctor model.Doctor
func (_e *MockRepo_Expecter) UpdateDoctor(doctor interface{}) *MockRepo_UpdateDoctor_Call {
	return &MockRepo_UpdateDoctor_Call{Call: _e.mock.On("UpdateDoctor", doctor)}
}

func (_c *MockRepo_UpdateDoctor_Call) Run(run func(doctor model.Doctor)) *MockRepo_UpdateDoctor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Doctor))
	})
	return _c
}

func (_c *MockRepo_UpdateDoctor_Call) Return(_a0 error) *MockRepo_UpdateDoctor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdateDoctor_Call) RunAndReturn(run func(model.Doctor) error) *MockRepo_UpdateDoctor_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePatient provides a mock function with given fields: patient
func (_m *MockRepo) UpdatePatient(patient model.Patient) error {
	ret := _m.Called(patient)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePatient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Patient) error); ok {
		r0 = rf(patient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdatePatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePatient'
type MockRepo_UpdatePatient_Call struct {
	*mock.Call
}

// UpdatePatient is a helper method to define mock.On call
//   - patient model.Patient
func (_e *MockRepo_Expecter) UpdatePatient(patient interface{}) *MockRepo_UpdatePatient_Call {
	return &MockRepo_UpdatePatient_Call{Call: _e.mock.On("UpdatePatient", patient)}
}

func (_c *MockRepo_UpdatePatient_Call) Run(run func(patient model.Patient)) *MockRepo_UpdatePatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Patient))
	})
	return _c
}

func (_c *MockRepo_UpdatePatient_Call) Return(_a0 error) *MockRepo_UpdatePatient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdatePatient_Call) RunAndReturn(run func(model.Patient) error) *MockRepo_UpdatePatient_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePatientMedicine provides a mock function with given fields: patientId, medicines
func (_m *MockRepo) UpdatePatientMedicine(patientId int, medicines []model.Medicine) error {
	ret := _m.Called(patientId, medicines)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePatientMedicine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []model.Medicine) error); ok {
		r0 = rf(patientId, medicines)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdatePatientMedicine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePatientMedicine'
type MockRepo_UpdatePatientMedicine_Call struct {
	*mock.Call
}

// UpdatePatientMedicine is a helper method to define mock.On call
//   - patientId int
//   - medicines []model.Medicine
func (_e *MockRepo_Expecter) UpdatePatientMedicine(patientId interface{}, medicines interface{}) *MockRepo_UpdatePatientMedicine_Call {
	return &MockRepo_UpdatePatientMedicine_Call{Call: _e.mock.On("UpdatePatientMedicine", patientId, medicines)}
}

func (_c *MockRepo_UpdatePatientMedicine_Call) Run(run func(patientId int, medicines []model.Medicine)) *MockRepo_UpdatePatientMedicine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]model.Medicine))
	})
	return _c
}

func (_c *MockRepo_UpdatePatientMedicine_Call) Return(_a0 error) *MockRepo_UpdatePatientMedicine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdatePatientMedicine_Call) RunAndReturn(run func(int, []model.Medicine) error) *MockRepo_UpdatePatientMedicine_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePatientVaccineHistory provides a mock function with given fields: patientId, vaccineHistory
func (_m *MockRepo) UpdatePatientVaccineHistory(patientId int, vaccineHistory []model.VaccineHistory) error {
	ret := _m.Called(patientId, vaccineHistory)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePatientVaccineHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []model.VaccineHistory) error); ok {
		r0 = rf(patientId, vaccineHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdatePatientVaccineHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePatientVaccineHistory'
type MockRepo_UpdatePatientVaccineHistory_Call struct {
	*mock.Call
}

// UpdatePatientVaccineHistory is a helper method to define mock.On call
//   - patientId int
//   - vaccineHistory []model.VaccineHistory
func (_e *MockRepo_Expecter) UpdatePatientVaccineHistory(patientId interface{}, vaccineHistory interface{}) *MockRepo_UpdatePatientVaccineHistory_Call {
	return &MockRepo_UpdatePatientVaccineHistory_Call{Call: _e.mock.On("UpdatePatientVaccineHistory", patientId, vaccineHistory)}
}

func (_c *MockRepo_UpdatePatientVaccineHistory_Call) Run(run func(patientId int, vaccineHistory []model.VaccineHistory)) *MockRepo_UpdatePatientVaccineHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]model.VaccineHistory))
	})
	return _c
}

func (_c *MockRepo_UpdatePatientVaccineHistory_Call) Return(_a0 error) *MockRepo_UpdatePatientVaccineHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdatePatientVaccineHistory_Call) RunAndReturn(run func(int, []model.VaccineHistory) error) *MockRepo_UpdatePatientVaccineHistory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuestionAnswer provides a mock function with given fields: questionId, answer, doctorId
func (_m *MockRepo) UpdateQuestionAnswer(questionId int, answer string, doctorId int) error {
	ret := _m.Called(questionId, answer, doctorId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestionAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, int) error); ok {
		r0 = rf(questionId, answer, doctorId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepo_UpdateQuestionAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestionAnswer'
type MockRepo_UpdateQuestionAnswer_Call struct {
	*mock.Call
}

// UpdateQuestionAnswer is a helper method to define mock.On call
//   - questionId int
//   - answer string
//   - doctorId int
func (_e *MockRepo_Expecter) UpdateQuestionAnswer(questionId interface{}, answer interface{}, doctorId interface{}) *MockRepo_UpdateQuestionAnswer_Call {
	return &MockRepo_UpdateQuestionAnswer_Call{Call: _e.mock.On("UpdateQuestionAnswer", questionId, answer, doctorId)}
}

func (_c *MockRepo_UpdateQuestionAnswer_Call) Run(run func(questionId int, answer string, doctorId int)) *MockRepo_UpdateQuestionAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepo_UpdateQuestionAnswer_Call) Return(_a0 error) *MockRepo_UpdateQuestionAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepo_UpdateQuestionAnswer_Call) RunAndReturn(run func(int, string, int) error) *MockRepo_UpdateQuestionAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
